### ISSUE TITLE
Slow to (re)compile

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-rust-sdk#106]
@martinetd was surprised by the long (re)compilation times: https://github.com/matrix-org/matrix-rust-sdk/pull/104#issuecomment-705568647.

I've played around with this locally because I suspected Ruma would have a similar problem, but surprisingly the ruma-client `hello_world` example recompiles in roughly 3 seconds on my machine while the matrix_sdk `login` example takes almost 6 seconds on average.

Here's some things that could help that I haven't tried yet:

1. installing LLVMs linker, lld and using that by creating `.cargo/config.toml` with

   ```toml
   # adjust to whatever target you are building for
   [target.x86_64-unknown-linux-gnu]
   rustflags = [
       "-C", "link-arg=-fuse-ld=lld",
   ]
   ```

2. building all dependencies in release mode, which *may* reduce the size of intermediary artifacts and thus improve relinking time, by adding the following to the `Cargo.toml` of a project using matrix_sdk (this won't work in the workspace itself because it doesn't apply to workspace crates):

   ```toml
   [profile.dev.package."*"]
   opt-level = 2
   ```

   (for more info see [the Cargo Book](https://doc.rust-lang.org/cargo/reference/profiles.html#overrides))

Separately from that, I've been thinking about having feature flags in Ruma such that you could choose to only have request-sending + response-receiving generated rather than getting all of request-{sending,receiving} + response-{sending,receiving}.

**Comment by martinetd** [comment]
Thanks, that's already a great improvement just from switching linker! I'll give it a try :)

Iirc my second problem was large types (had to add a type_length_limit directive at top of the sources) that I had read could be slow at the time... I'm not sure if that improved or if I still need to look into putting a key element in a Box to break the chain somewhere; I've honestly not touched at my client for a while now...

**Comment by jplatte** [comment]
Here's what you need for mold (lld is also be faster than the gnu linker, but not nearly as fast as mold):

```toml
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=mold",
]
```
