### ISSUE TITLE
Example for reading and writing messages in an encrypted room.

### ISSUE THREAD

**Issue by gmosx** [matrix-org/matrix-rust-sdk#135]
I understand that the matrix-sdk supports  end-to-end encryption.

However it's not clear how this could work. A small example showing how to read messages from an encrypted room and how to send messages to an encrypted room would be **extremely helpful**. :pray: 

I have looked at the [cross_signing_bootstrap](https://github.com/matrix-org/matrix-rust-sdk/blob/master/matrix_sdk/examples/cross_signing_bootstrap.rs) example which sounds related, but I am not sure how to proceed.

**Comment by poljar** [comment]
Encryption will work transparently as long as the `encryption` feature is enabled, if the room the message is being sent to is encrypted the message will be encrypted. Decryption works transparently as well, if a message can be decrypted it will be decrypted.

**Comment by gmosx** [comment]
Hmm, didn't work transparently :( I see this:

![image](https://user-images.githubusercontent.com/37342/107154840-b8f7ad00-697d-11eb-8926-78887abab2e0.png)

**Comment by poljar** [comment]
Well it seems like it did encrypt stuff transparently, though Element didn't receive the key to decrypt the message. Could you take a look at the logs in Element in the developer console, there is likely an error.

What version are you using? If you're on 0.2 could you try master, there might be an error with how the signatures are created on 0.2.

**Comment by gmosx** [comment]
I see errors like this one:

```
Error decrypting event (id=$KOq7-FkhhBuOxoleCCFOBu49PWNk5uQnFTX7RaF-r5I): DecryptionError[msg: The sender's device has not sent us the keys for this message., session: u/fm5I1qc5OhOVTu1q/gbhw+QwUXnIaA+XttaOzN500|BiWRaT9sY/7hV7Urr+8yflEADKPCYg96sl9QGShxfoY]
```

I am using this version:

```toml
[dependencies.matrix-sdk]
git = "https://github.com/matrix-org/matrix-rust-sdk.git"
rev = "7b8d2b5319bebcd95eee2c10b1e59641dea46e8e"
default-features = false
features = ["encryption", "rustls-tls", "markdown"]
```
