### ISSUE TITLE
appservice: how to join a room/get all invited rooms?

### ISSUE THREAD

**Issue by Zwelf** [matrix-org/matrix-rust-sdk#1354]
My question is: How do I get the invited rooms for the AS user and join the rooms. My code looks like this:

```rs
use matrix_sdk_appservice::matrix_sdk::config::SyncSettings;
use matrix_sdk_appservice::{AppService, AppServiceRegistration, UserBuilder};
use std::time::Duration;

#[tokio::main]
async fn main() {
    let registration =
        AppServiceRegistration::try_from_yaml_file("registration.yaml")
            .unwrap();

    let appservice = AppService::builder(
        "http://localhost:6867".try_into().unwrap(),
        "ddnet.org".try_into().unwrap(),
        registration,
    )
        .build()
        .await
        .unwrap();

    let _ = appservice.register_user("_testing_bot", None).await;
    // let user = appservice.user(Some("_testing_bot")).await.unwrap();
    let user = UserBuilder::new(&appservice, "_testing_bot")
        .device_id(Some("testing-rs".into()))
        .login()
        .build()
        .await
        .unwrap();

    let sync_settings = SyncSettings::new().timeout(Duration::from_millis(0));
    user.sync_once(sync_settings).await.unwrap();
    for room in user.invited_rooms() {
        room.accept_invitation().await.unwrap();
    }
}
```
<details>

`registration.yaml`
```
# registration.yaml

# An ID which is unique across all application services on your homeserver. This should never be changed once set.
id: "testing"

# this is the base URL of the application service
url: "http://127.0.0.1:6166"

# This is the token that the AS should use as its access_token when using the Client-Server API
# This can be anything you want.
as_token: 463e8548-3d50-4017-a758-7eba6e5e628d

# This is the token that the HS will use when sending requests to the AS.
# This can be anything you want.
hs_token: 4b173650-bc2a-4c12-ad33-c448305b8c7b

# this is the local part of the desired user ID for this AS (in this case @logging:localhost)
sender_localpart: _testing_bot
namespaces:
  users:
    - exclusive: true
      regex: '@_testing_.+:ddnet.org'
  rooms: []
  aliases:
    - exclusive: true
      regex: '#_testing_.+:ddnet.org'
```

</details>

But the conduit thread handling this request panics here <https://gitlab.com/famedly/conduit/-/blob/c6e3438e7639abeb23f6a3adf296a60efbf5bc57/src/api/client_server/sync.rs#L61>:
```
thread 'tokio-runtime-worker' panicked at 'user is authenticated', /usr/src/conduit/src/api/client_server/sync.rs:61:44
```

This results in my code not being able to sync and panic due to the lack of response and closed tcp socket from conduit:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Http(Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(6867), path: "/_matrix/client/versions", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }))', as/src/bin/as.rs:53:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

AFAIK if I don't sync `user.invited_rooms()` always returns an empty array.
