### ISSUE TITLE
Can't install recent versions: conflict when linking to `sqlite3`

### ISSUE THREAD

**Issue by Pamplemousse** [matrix-org/matrix-rust-sdk#3689]
Hi there :wave: 

My `Cargo.toml` currently contains 
```
# ...
[dependencies]
matrix-sdk = { git = "https://github.com/matrix-org/matrix-rust-sdk.git", rev = "d9f3a5476ed656a877717c8df776999df035ea99" }
rusqlite = { version = "0.28.0", features = ["chrono"] }                                                                                                                                                  
r2d2 = "0.8.10"                                                                                                                                                                                           
r2d2_sqlite = "0.21.0"
# ...
```

which works fine.

However, I would like to benefit from recent bugfixes (such as #3604), so I try
```
[dependencies]
matrix-sdk = { git = "https://github.com/matrix-org/matrix-rust-sdk.git", rev = "cb4c5752345c72c6be10fb4dc5f1926af2428e43" }
rusqlite = { version = "0.28.0", features = ["chrono"] }                                                                                                                                                  
r2d2 = "0.8.10"                                                                                                                                                                                           
r2d2_sqlite = "0.21.0"
```

which fails with the following message:

```
    Updating git repository `https://github.com/matrix-org/matrix-rust-sdk.git`
    Updating crates.io index
    Updating git repository `https://github.com/ruma/ruma`
    Updating git repository `https://github.com/matrix-org/vodozemac/`
error: failed to select a version for `libsqlite3-sys`.
    ... required by package `rusqlite v0.30.0`
    ... which satisfies dependency `rusqlite = "^0.30.0"` of package `matrix-sdk-sqlite v0.7.0 (https://github.com/matrix-org/matrix-rust-sdk.git#48f11ea0)`
    ... which satisfies git dependency `matrix-sdk-sqlite` of package `matrix-sdk v0.7.1 (https://github.com/matrix-org/matrix-rust-sdk.git#48f11ea0)`
    ... which satisfies git dependency `matrix-sdk` of package `alfred v0.1.0 (/home/pamplemousse/Workspace/Alfred)`
versions that meet the requirements `^0.27.0` are: 0.27.0

the package `libsqlite3-sys` links to the native library `sqlite3`, but it conflicts with a previous package which links to `sqlite3` as well:
package `libsqlite3-sys v0.25.2`
    ... which satisfies dependency `libsqlite3-sys = "^0.25.0"` (locked to 0.25.2) of package `rusqlite v0.28.0`
    ... which satisfies dependency `rusqlite = "^0.28.0"` (locked to 0.28.0) of package `alfred v0.1.0 (/home/pamplemousse/Workspace/Alfred)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the `links = "sqlite3"` value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `libsqlite3-sys` which could resolve this conflict
```

Note that I get the same error with `matrix-sdk = { git = "https://github.com/matrix-org/matrix-rust-sdk.git", version = "0.7.1" }`.

I have tried to tweak versions of `rusqlite`, and `r2d2_sqlite` without any success.
I am a little confused about what is causing the issue, even more about ideas on how to solve this... Any help appreciated.

**Comment by poljar** [comment]
We're lagging a bit behind on the `rusqlite` version we're using,  which puts limits on the `r2d2_sqlite` version you can pick. You do need to pick the same version of `rusqlite` the `matrix-sdk` crate is using.

> I have tried to tweak versions of rusqlite, and r2d2_sqlite without any success.

This seems to work:

```toml
[dependencies]
matrix-sdk = { git = "https://github.com/matrix-org/matrix-rust-sdk.git", rev = "cb4c5752345c72c6be10fb4dc5f1926af2428e43" }
rusqlite = { version = "0.30.0", features = ["chrono"] }                                                                                                                                                  
r2d2 = "0.8.10"                                                                                                                                                                                           
r2d2_sqlite = "0.23.0"
```
