### ISSUE TITLE
Futures-timer pulls in wasm specific deps on non-wasm targets.

### ISSUE THREAD

**Issue by poljar** [matrix-org/matrix-rust-sdk#46]

**Comment by poljar** [comment]
The dependency definition has been fixed to require the `wasm-bindgen` feature only on the WASM target, sadly this doesn't work as of yet.

It will start working once https://github.com/rust-lang/cargo/issues/7914 lands.

**Comment by poljar** [comment]
It's possible to avoid this using a stable version of Rust by using the new dependency resolver and Rust 1.51 or later, relevant news section can be found [here](https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#cargos-new-feature-resolver).

Though end users of the SDK will need to configure this in their own `Cargo.toml`. For refrerence this is the setting.

```toml


[package]
resolver = "2"
# Or if you're using a workspace
[workspace]
resolver = "2"
```
