### ISSUE TITLE
Depending on matrix-sdk

### ISSUE THREAD

**Issue by DevinR528** [matrix-org/matrix-rust-sdk#47]
In order to get the messages feature turned on, I had to
```toml
matrix-sdk = "0.1.0"
matrix-sdk-base = "0.1.0" # in order to turn on the default features
```
in the Cargo.toml. Is this expected?
