### ISSUE TITLE
Publish `matrix-sdk-appservice` crate on crates.io

### ISSUE THREAD

**Issue by dulguun0225** [matrix-org/matrix-rust-sdk#669]
I wanted to use `matrix-sdk-appservice`. But couldn't find it on [crates.io](https://crates.io/search?q=matrix-sdk-appservice).

**Comment by gnunicorn** [comment]
Hello @dulguun0225 ,

sorry to disappoint you but `matrix-sdk-appservice` is not yet in a state that we want to release it to the wild. You can follow the current state at #228 or just use it from our git repo until then - just make sure your other dependency follow that pattern:

```toml
[dependencies]
matrix-sdk = { git = "https://github.org/matrix-org/matrix-rust-sdk" }
matrix-sdk-appservice = { git = "https://github.org/matrix-org/matrix-rust-sdk" }

```

I've just pushed a reservation to crates.io that makes this more explicit, too. Closing this issue.
