### ISSUE TITLE
Improve getting started code example

### ISSUE THREAD

**Issue by ratzupaltuff** [matrix-org/matrix-rust-sdk#875]
**Describe the bug**
When I copy paste the "Getting started" Code to a fresh rust project it does not compile.
Other Crates have documentation what modules need to be imported in order to use the example, this one does not.
The compiler says use std::convert::TryFrom; is a unnecessary Import.

**To Reproduce**
Go to https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk/index.html and copy the code.
Create a new Project with `cargo new xyz`
Paste Code to main.rs
Run `cargo run`

My Cargo.toml:
```toml
[package]
name = "xyz"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tokio = { version = "1.20.0", features = ["full"] }
#matrix-sdk = "0.5"

[dependencies.matrix-sdk]
version = "0.5.0"
#default-features = true
```

My src/main.rs
```rust
//use std::convert::TryFrom;
use matrix_sdk::{
    Client, config::SyncSettings,
    ruma::{user_id, events::room::message::SyncRoomMessageEvent},
};

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let user = user_id!("@test:matrix.org");
    let client = Client::builder().user_id(user).build().await?;

    // First we need to log in.
    client.login_username(user, "password").send().await?;

    client
        .register_event_handler(|ev: SyncRoomMessageEvent| async move {
            println!("Received a message {:?}", ev);
        })
        .await;

    // Syncing is important to synchronize the client state with the server.
    // This method will never return.
    client.sync(SyncSettings::default()).await;

    Ok(())
}
```

**Expected behavior**
Clear documentation on necessary Imports and a working example without unused imports.

**Desktop (please complete the following information):**
 - OS: Archlinux

**Additional context**
I am new to Rust and this SDK so maybe there are simple answers. Please be kind in your answers.
I opened this Issue to give you a perspective what would be helpful for me as a beginner.
